import { StyleSheet } from 'react-native';
import { typography as t } from '@/theme/tokens';

export const loginColors = {
  background: '#F8F6F2',
  primary: '#10584F',
  title: '#104D44',
  muted: '#727A80',
  ink: '#303C43',
  border: '#DADDE0',
  danger: '#B83D3D',
};
const p = loginColors;

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  scroll: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 20, paddingTop: 32 },
  content: { width: '100%', maxWidth: 440, alignSelf: 'center' },
  decoration: { ...StyleSheet.absoluteFill, overflow: 'hidden' },
  orbit: { position: 'absolute', borderWidth: 1, borderColor: 'rgba(16,88,79,0.10)' },
  node: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#E0E6E1',
  },
  brand: { alignItems: 'center' },
  logo: { width: 104, height: 104 },
  brandName: {
    fontFamily: t.bold,
    fontSize: 39,
    lineHeight: 48,
    color: p.title,
    textAlign: 'center',
    marginTop: -4,
  },
  intro: { alignItems: 'center', marginTop: 34, marginBottom: 28, gap: 8 },
  title: { fontFamily: t.bold, fontSize: 34, lineHeight: 46, color: p.title, textAlign: 'center' },
  subtitle: { fontSize: 15, lineHeight: 25, color: p.muted, textAlign: 'center' },
  form: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#EAE5DD',
    padding: 18,
    gap: 18,
    shadowColor: '#5C503F',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.035,
    shadowRadius: 20,
    elevation: 1,
  },
  field: { gap: 7 },
  label: { fontFamily: t.medium, fontSize: 14, lineHeight: 22, color: p.ink },
  inputRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 12,
    minHeight: 52,
    paddingHorizontal: 10,
    gap: 8,
    backgroundColor: '#FCFCFC',
  },
  focusedInput: { borderColor: p.primary, backgroundColor: '#FCFEFD' },
  invalidInput: { borderColor: p.danger, backgroundColor: '#FFF9F8' },
  input: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 12,
    fontFamily: t.regular,
    fontSize: 15,
    lineHeight: 24,
    color: p.ink,
    textAlign: 'right',
  },
  enteredInput: { textAlign: 'left', writingDirection: 'ltr' },
  eye: {
    minWidth: 44,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  fieldError: { color: p.danger, fontSize: 12, lineHeight: 20 },
  error: {
    backgroundColor: '#FFF4F2',
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 8,
  },
  errorText: { flex: 1, color: p.danger, fontSize: 13, lineHeight: 22 },
  primary: {
    minHeight: 52,
    borderRadius: 13,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    backgroundColor: p.primary,
  },
  primaryText: {
    flex: 1,
    color: '#fff',
    fontFamily: t.bold,
    fontSize: 17,
    lineHeight: 26,
    textAlign: 'center',
  },
  buttonIcon: { width: 24, alignItems: 'center', justifyContent: 'center' },
  signup: { marginTop: 32, paddingHorizontal: 7, gap: 17 },
  signupHint: { color: p.muted, fontSize: 16, lineHeight: 26, textAlign: 'center' },
  secondary: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: p.primary,
    borderRadius: 13,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: {
    color: p.title,
    fontFamily: t.bold,
    fontSize: 17,
    lineHeight: 26,
    textAlign: 'center',
  },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.65 },
});
