import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.pageColor },
  list: {
    paddingHorizontal: hp(1.9),
    paddingTop: hp(0.9),
    paddingBottom: hp(10),
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: hp(1.9),
    padding: hp(1.6),
    marginBottom: hp(1.4),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  iconBox: {
    width: hp(5.4),
    height: hp(5.4),
    borderRadius: hp(1.4),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hp(1.6),
  },
  labelContainer: { flex: 1 },
  menuLabel: {
    fontSize: hp(1.8),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: 2,
  },
  menuSubtitle: { fontSize: hp(1.4), fontFamily: FONTS.fontFamilyRegular, color: COLORS.darkgray2 },

  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(1.2),
    paddingVertical: hp(1.6),
    borderRadius: hp(1.9),
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    gap: 10,
  },
  logoutIconBox: {
    width: hp(3.5),
    height: hp(3.5),
    borderRadius: hp(0.9),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ scaleX: -1 }],
  },
  logoutText: { fontSize: hp(1.8), fontFamily: FONTS.fontFamilyBold, color: COLORS.error },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(8),
  },
  logoutModal: {
    backgroundColor: COLORS.white,
    width: '100%',
    borderRadius: 24,
    padding: wp(8),
    alignItems: 'center',
  },
  modalIconBox: {
    width: hp(9.4),
    height: hp(9.4),
    borderRadius: hp(4.7),
    backgroundColor: '#FEF2F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  modalTitle: {
    fontSize: hp(2.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: 10,
  },
  modalDesc: {
    fontSize: hp(1.6),
    color: COLORS.darkgray2,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: hp(3.5),
  },
  modalActions: { flexDirection: 'row', gap: 12, width: '100%' },
  cancelBtn: {
    flex: 1,
    height: hp(5.9),
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelBtnText: { fontSize: hp(1.8), fontFamily: FONTS.fontFamilyBold, color: '#4B5563' },
  confirmBtn: {
    flex: 1,
    height: hp(5.9),
    borderRadius: 12,
    backgroundColor: COLORS.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmBtnText: { fontSize: hp(1.8), fontFamily: FONTS.fontFamilyBold, color: COLORS.white },
});
