import { StyleSheet } from 'react-native';
import { palette as p, typography as t } from '@/theme/tokens';
export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    minHeight: 55,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  headerTitle: { fontFamily: t.bold, fontSize: 17, color: p.deep },
  iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  backButton: { backgroundColor: p.soft, borderRadius: 14, borderWidth: 1, borderColor: p.border },
  cartBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    minWidth: 19,
    borderRadius: 12,
    backgroundColor: p.primary,
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  cartBadgeText: { color: '#fff', fontSize: 10, lineHeight: 19 },
  page: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 15,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  identity: { gap: 3 },
  meta: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' },
  category: { fontSize: 12, color: p.muted },
  stock: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#E2F4E9',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  stockText: { color: p.primary, fontSize: 12 },
  out: { backgroundColor: '#FAE8E2' },
  dot: { width: 6, height: 6, borderRadius: 4, backgroundColor: p.primary },
  title: { fontFamily: t.bold, fontSize: 26, lineHeight: 36, color: p.deep, marginTop: 7 },
  codeRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 3 },
  code: { fontSize: 13, color: p.muted },
  prices: {
    flexDirection: 'row-reverse',
    backgroundColor: '#EAF6EF',
    borderRadius: 16,
    padding: 16,
    gap: 14,
  },
  priceCell: { flex: 1, minWidth: 0, gap: 8 },
  priceLabel: { fontSize: 13, color: p.primary },
  price: {
    fontSize: 23,
    lineHeight: 31,
    fontFamily: t.bold,
    color: '#08634E',
    writingDirection: 'ltr',
  },
  secondaryPrice: { fontSize: 20 },
  divider: { width: 1, backgroundColor: '#BCDCCE' },
  dividerHorizontal: { height: 1, backgroundColor: '#BCDCCE', width: '100%' },
  quantitySection: { gap: 9 },
  sectionTitle: { fontFamily: t.bold, color: p.deep, fontSize: 18, lineHeight: 28 },
  stepper: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 12,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  step: {
    width: 48,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2ED',
  },
  plus: { backgroundColor: p.primary },
  quantity: { minWidth: 64, textAlign: 'center', fontFamily: t.bold, fontSize: 23 },
  disabled: { opacity: 0.4 },
  centerCaption: { fontSize: 12, lineHeight: 20, color: p.muted, textAlign: 'center' },
  about: { borderTopWidth: 1, borderColor: p.border, paddingTop: 18, gap: 10 },
  description: { color: '#4E645A', fontSize: 15, lineHeight: 27, writingDirection: 'rtl' },
  more: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    alignSelf: 'flex-end',
  },
  moreText: { fontFamily: t.bold, color: p.primary, fontSize: 13 },
  date: { color: p.muted, fontSize: 11, borderTopWidth: 1, borderColor: p.border, paddingTop: 12 },
  footer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: p.border,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  total: { minWidth: 105 },
  totalPrice: {
    color: p.deep,
    fontFamily: t.bold,
    fontSize: 20,
    lineHeight: 30,
    writingDirection: 'ltr',
  },
  caption: { color: p.muted, fontSize: 11 },
  footerButton: { flex: 1, minWidth: 150 },
  stacked: { flexDirection: 'column', alignItems: 'stretch' },
  feedback: { color: p.primary, fontSize: 12 },
  notice: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E2F4E9',
    borderRadius: 12,
    padding: 13,
  },
  noticeText: { fontSize: 13, color: p.primary, flexShrink: 1 },
  updating: {
    flexDirection: 'row-reverse',
    gap: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  error: { backgroundColor: '#FFF2E9', padding: 14, borderRadius: 12, gap: 10 },
  errorText: { fontSize: 13, color: '#8C4B22', textAlign: 'center' },
  state: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  stateTitle: { fontFamily: t.bold, fontSize: 22, color: p.deep, textAlign: 'center' },
  stateText: { fontSize: 14, color: p.muted, textAlign: 'center' },
  skeletonHero: { height: 315, backgroundColor: '#E8EDE7', borderRadius: 20 },
  skeletonLine: { height: 20, backgroundColor: '#E8EDE7', borderRadius: 6, alignSelf: 'flex-end' },
  skeletonPrice: { height: 100, backgroundColor: '#E8EDE7', borderRadius: 15 },
});
