import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  headerFloating: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(5),
    zIndex: 100,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  headerBtn: {
    width: hp(4.5),
    height: hp(4.5),
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(10px)',
  },
  headerBtnLib: {
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(10px)',
  },
  headerBtnText: {
    color: COLORS.white,
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyBold,
  },
  favActive: {
    backgroundColor: '#FF4136',
  },
  heroSection: {
    height: hp(55),
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productWrapper: {
    width: wp(60),
    height: hp(40),
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    marginTop: hp(5),
  },
  productCover: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  contentMain: {
    marginTop: -hp(6),
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    paddingHorizontal: wp(6),
    paddingTop: hp(4),
    flex: 1,
  },
  metaInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  mainTag: {
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.6),
    backgroundColor: '#F0F9FF',
    borderRadius: 8,
  },
  mainTagText: {
    color: '#0EA5E9',
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyBold,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingValue: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
    marginLeft: 5,
    color: COLORS.charcoal,
  },
  reviewsCount: {
    fontSize: hp(1.4),
    color: COLORS.gray,
    marginLeft: 5,
  },
  productTitle: {
    fontSize: hp(2.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    lineHeight: hp(3.3),
  },
  authorName: {
    fontSize: hp(1.6),
    color: COLORS.primary,
    fontFamily: FONTS.fontFamilyMedium,
    marginTop: hp(0.5),
  },
  tabsContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    marginBottom: hp(2.5),
  },
  tab: {
    flex: 1,
    paddingVertical: hp(1.5),
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: COLORS.primary,
  },
  tabText: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.gray,
  },
  tabTextActive: {
    color: COLORS.primary,
    fontFamily: FONTS.fontFamilyBold,
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: hp(3.5),
    backgroundColor: '#FAFAFA',
    padding: wp(4),
    borderRadius: 20,
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
  },
  statIconWrap: {
    marginBottom: 8,
  },
  statVal: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  statLabel: {
    fontSize: hp(1.2),
    color: COLORS.gray,
    textTransform: 'uppercase',
  },
  descSection: {
    marginTop: hp(1),
  },
  descriptionSection: {
    marginTop: hp(1),
    marginBottom: hp(10),
  },
  sectionTitle: {
    fontSize: hp(1.9),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(1),
  },
  descriptionText: {
    fontSize: hp(1.5),
    color: '#6B7280',
    lineHeight: hp(2.6),
    fontFamily: FONTS.fontFamilyRegular,
  },
  relatedSection: {
    marginTop: hp(4),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(1.5),
  },
  viewAll: {
    fontSize: hp(1.4),
    color: COLORS.primary,
    fontFamily: FONTS.fontFamilyBold,
  },
  horizontalScroll: {
    paddingLeft: wp(0.5),
    gap: wp(1.5),
    paddingTop: hp(0.1),
  },
  relatedItem: {
    width: wp(35),
    marginRight: wp(4),
  },
  relatedImage: {
    width: '100%',
    height: hp(18),
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  relatedTitle: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginTop: 8,
  },
  relatedPrice: {
    fontSize: hp(1.3),
    color: COLORS.primary,
    fontFamily: FONTS.fontFamilyBold,
    marginTop: 2,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(6),
    paddingTop: hp(2),
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    justifyContent: 'space-between',
  },
  priceSection: {
    flex: 0.4,
  },
  priceTag: {
    fontSize: hp(2.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  vatInfo: {
    fontSize: hp(1.2),
    color: COLORS.gray,
  },
  actionRow: {
    flex: 0.6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: wp(3),
  },
  secondaryAction: {
    width: hp(6.5),
    height: hp(6.5),
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryAction: {
    flex: 1,
    height: hp(6.5),
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  gradientCta: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  ctaText: {
    color: COLORS.white,
    fontSize: hp(1.8),
    fontFamily: FONTS.fontFamilyBold,
  },
  reviewsSection: {
    marginTop: hp(4),
  },
  reviewForm: {
    backgroundColor: '#F9FAFB',
    padding: wp(4),
    borderRadius: 16,
    marginBottom: hp(3),
  },
  ratingInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(2),
  },
  inputLabel: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.charcoal,
  },
  starsRow: {
    flexDirection: 'row',
    gap: 5,
  },
  input: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    fontSize: hp(1.5),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.charcoal,
    marginBottom: hp(1.5),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  textArea: {
    height: hp(12),
    textAlignVertical: 'top',
  },
  submitBtn: {
    height: hp(6),
    borderRadius: 12,
    overflow: 'hidden',
    marginTop: hp(1),
    width: '100%',
  },
  submitGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitBtnText: {
    color: COLORS.white,
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
  },
  reviewsList: {
    marginTop: hp(1),
  },
  reviewItem: {
    paddingVertical: hp(2),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  reviewTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  reviewerName: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  reviewDate: {
    fontSize: hp(1.2),
    color: COLORS.gray,
  },
  reviewStars: {
    flexDirection: 'row',
    marginBottom: 4,
    gap: 2,
  },
  reviewComment: {
    fontSize: hp(1.5),
    color: '#4B5563',
    lineHeight: hp(2.1),
    fontFamily: FONTS.fontFamilyRegular,
  },
  priceCardsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    flexGrow: 1,
  },
  priceStepCard: {
    width: wp(25),
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: hp(1.4),
    paddingHorizontal: wp(2.5),
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: hp(11),
  },
  priceStepCardHighlighted: {
    backgroundColor: '#E8F8F5',
    borderColor: '#A7F3D0',
    borderWidth: 1.5,
  },
  priceCardIconBox: {
    width: hp(3.6),
    height: hp(3.6),
    borderRadius: 10,
    backgroundColor: '#FFF3E0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(0.8),
  },
  priceCardIconBoxMerchant: {
    backgroundColor: '#D1FAE5',
  },
  priceCardIconBoxExpected: {
    backgroundColor: '#E6F8F4',
  },
  priceCardLabel: {
    fontSize: hp(1.25),
    fontFamily: FONTS.fontFamilyMedium,
    color: '#64748B',
    marginBottom: 4,
    textAlign: 'center',
  },
  priceCardLabelMerchant: {
    color: '#0F766E',
    fontFamily: FONTS.fontFamilyBold,
  },
  priceCardValue: {
    fontSize: hp(2.0),
    fontFamily: FONTS.fontFamilyBold,
    color: '#0F172A',
    textAlign: 'center',
  },
  priceCardValueMerchant: {
    color: '#042F2E',
    fontSize: hp(2.1),
  },
  priceStepArrow: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
});
