import { StyleSheet } from 'react-native';
import { typography as t } from '@/theme/tokens';
export const colors = {
  background: '#F7F5F1',
  primary: '#14594C',
  deep: '#103F37',
  muted: '#6D7579',
  border: '#E3E1DC',
  soft: '#EAF4ED',
  danger: '#AD443D',
};
const p = colors;
export const styles = StyleSheet.create({
  flex: { flex: 1 },
  content: {
    width: '100%',
    maxWidth: 660,
    alignSelf: 'center',
    padding: 16,
    paddingBottom: 28,
    gap: 12,
  },
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 8,
  },
  heading: { flex: 1 },
  greeting: { fontSize: 14, color: p.muted },
  title: { fontFamily: t.bold, fontSize: 28, lineHeight: 39, color: p.deep },
  subtitle: { fontSize: 13, color: p.muted, lineHeight: 22 },
  brand: { flexDirection: 'row-reverse', gap: 5, alignItems: 'center', marginTop: 3 },
  logo: { width: 27, height: 27 },
  brandName: { fontFamily: t.bold, fontSize: 19, color: p.deep },
  summary: { flexDirection: 'row-reverse', gap: 8, marginTop: 16, marginBottom: 4 },
  metric: {
    flex: 1,
    padding: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 14,
    gap: 5,
  },
  metricLabel: { fontSize: 12, color: p.muted },
  metricRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  number: { fontFamily: t.bold, fontSize: 30, lineHeight: 38, color: p.deep },
  search: {
    flexDirection: 'row-reverse',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 13,
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
    marginTop: 12,
  },
  input: {
    flex: 1,
    minWidth: 0,
    minHeight: 50,
    fontFamily: t.regular,
    fontSize: 13,
    color: p.deep,
    textAlign: 'right',
    paddingVertical: 12,
  },
  iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  filters: { flexDirection: 'row', flexGrow: 1, gap: 8, paddingVertical: 14 },
  pill: {
    minHeight: 44,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 13,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  active: { backgroundColor: p.primary, borderColor: p.primary },
  pillText: { fontSize: 12, color: p.deep, fontFamily: t.medium },
  white: { color: '#fff' },
  section: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    gap: 10,
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 4,
  },
  sectionTitle: { fontSize: 17, fontFamily: t.bold, color: p.deep, flexShrink: 1 },
  hint: { fontSize: 12, color: p.muted, lineHeight: 21 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 17,
    borderWidth: 1,
    borderColor: p.border,
    padding: 14,
    gap: 12,
  },
  cardHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  orderId: { fontSize: 14, color: p.muted },
  badge: {
    backgroundColor: '#FAF2E5',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeDone: { backgroundColor: p.soft },
  badgeText: { fontSize: 12, color: p.deep },
  name: { fontSize: 20, lineHeight: 29, fontFamily: t.bold, color: p.deep },
  location: { flexDirection: 'row-reverse', alignItems: 'center', gap: 6 },
  address: { color: p.muted, fontSize: 13, lineHeight: 23, flexShrink: 1 },
  details: { gap: 7 },
  divider: { borderTopWidth: 1, borderColor: p.border, paddingTop: 12, gap: 8 },
  actions: { flexDirection: 'row-reverse', gap: 8 },
  secondary: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: p.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    padding: 8,
    gap: 8,
  },
  buttonText: {
    fontFamily: t.bold,
    color: p.deep,
    fontSize: 13,
    flexShrink: 1,
    textAlign: 'center',
  },
  primary: {
    backgroundColor: p.primary,
    minHeight: 46,
    borderRadius: 11,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    gap: 8,
  },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.7 },
  state: { alignItems: 'center', paddingVertical: 28, gap: 12 },
  center: { textAlign: 'center' },
  error: { fontSize: 13, lineHeight: 22, color: p.danger },
  notice: { backgroundColor: p.soft, padding: 12, borderRadius: 12, gap: 8 },
  overlay: { flex: 1, backgroundColor: 'rgba(13,39,30,0.35)', justifyContent: 'flex-end' },
  sheet: {
    maxHeight: '92%',
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    backgroundColor: p.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 12,
  },
  sheetBody: { gap: 12, paddingBottom: 12 },
  option: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    minHeight: 48,
    padding: 12,
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 12,
    backgroundColor: '#fff',
  },
  notes: {
    borderWidth: 1,
    borderColor: p.border,
    backgroundColor: '#fff',
    borderRadius: 12,
    minHeight: 90,
    textAlignVertical: 'top',
    padding: 12,
    color: p.deep,
    fontFamily: t.regular,
    textAlign: 'right',
    fontSize: 14,
  },
});
