import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(5),
  },
  card: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: hp(2.5),
    padding: hp(3),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
  },
  iconContainer: {
    width: hp(10),
    height: hp(10),
    borderRadius: hp(5),
    backgroundColor: '#FFF4EC',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(2),
    borderWidth: 2,
    borderColor: '#FFE0CC',
  },
  badge: {
    backgroundColor: '#FFF5F2',
    borderColor: COLORS.mainOrange,
    borderWidth: 1,
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.5),
    borderRadius: hp(1),
    marginBottom: hp(1.5),
  },
  badgeText: {
    color: COLORS.mainOrange,
    fontSize: hp(1.5),
    fontFamily: FONTS.fontFamilyBold,
  },
  title: {
    fontSize: hp(2.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(1),
    textAlign: 'center',
  },
  description: {
    fontSize: hp(1.6),
    color: COLORS.gray,
    textAlign: 'center',
    lineHeight: hp(2.4),
    marginBottom: hp(2.5),
    fontFamily: FONTS.fontFamilyRegular,
    paddingHorizontal: wp(2),
  },
  userInfoBox: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: hp(1.5),
    padding: hp(1.8),
    marginBottom: hp(2.5),
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(0.6),
  },
  infoLabel: {
    fontSize: hp(1.4),
    color: COLORS.gray,
    fontFamily: FONTS.fontFamilyMedium,
  },
  infoValue: {
    fontSize: hp(1.4),
    color: COLORS.charcoal,
    fontFamily: FONTS.fontFamilyBold,
  },
  buttonContainer: {
    width: '100%',
    gap: hp(1.2),
  },
  logoutBtn: {
    width: '100%',
    height: hp(5.5),
    borderRadius: hp(1.2),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FF4D4F',
    backgroundColor: '#FFF1F0',
  },
  logoutText: {
    color: '#FF4D4F',
    fontSize: hp(1.7),
    fontFamily: FONTS.fontFamilyBold,
  },
});
