import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.pageColor },
  scroll: { padding: wp(5), paddingBottom: hp(5) },
  statusCard: {
    backgroundColor: COLORS.white,
    padding: wp(5),
    borderRadius: 20,
    alignItems: 'center',
    marginBottom: hp(3),
  },
  statusBadge: {
    paddingHorizontal: wp(6),
    paddingVertical: hp(0.8),
    borderRadius: 30,
    marginBottom: 8,
  },
  statusText: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold },
  dateText: { fontSize: hp(1.5), color: COLORS.darkgray2, fontFamily: FONTS.fontFamilyRegular },
  sectionTitle: {
    fontSize: hp(1.9),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(1.5),
    marginTop: hp(1),
  },
  itemsContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: wp(4),
    gap: 15,
    marginBottom: hp(3),
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    paddingBottom: 15,
  },
  itemImage: {
    width: hp(7.1),
    height: hp(7.1),
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  itemInfo: { flex: 1, alignItems: 'flex-end' },
  itemTitle: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  itemQty: { fontSize: hp(1.3), color: COLORS.darkgray2, marginTop: 2 },
  itemPrice: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.mainOrange,
    marginTop: 4,
  },
  addressCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    padding: wp(4),
    borderRadius: 20,
    alignItems: 'center',
    gap: 15,
    marginBottom: hp(3),
  },
  addressIcon: {
    width: hp(5.2),
    height: hp(5.2),
    borderRadius: 12,
    backgroundColor: '#FFF0E9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressLabel: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  addressText: { fontSize: hp(1.5), color: COLORS.darkgray2, marginTop: 2, lineHeight: 18 },
  summaryCard: {
    backgroundColor: COLORS.white,
    padding: wp(5),
    borderRadius: 20,
    marginBottom: hp(2),
  },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  summaryLabel: { fontSize: hp(1.6), color: COLORS.darkgray2 },
  summaryValue: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  totalLabel: { fontSize: hp(1.9), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  totalValue: { fontSize: hp(2.1), fontFamily: FONTS.fontFamilyBold, color: COLORS.mainOrange },
  reorderBtn: {
    backgroundColor: COLORS.charcoal,
    height: hp(6),
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(2),
  },
  reorderText: { fontSize: hp(1.7), fontFamily: FONTS.fontFamilyBold, color: COLORS.white },
});
