import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.lightGrey },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(1.4),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray4,
  },
  backBtn: {
    width: hp(4.2),
    height: hp(4.2),
    borderRadius: hp(1.2),
    borderWidth: 1,
    borderColor: COLORS.gray5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: hp(2.0),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: hp(1.2),
    backgroundColor: COLORS.white,
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(1.4),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray4,
  },
  toggleLabel: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyMedium, color: COLORS.charcoal },
  list: { padding: hp(1.9), paddingBottom: hp(4.7) },
  notifCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.white,
    borderRadius: hp(1.6),
    padding: hp(1.6),
    marginBottom: hp(1.2),
    gap: hp(1.4),
  },
  unreadCard: { borderLeftWidth: 3, borderLeftColor: COLORS.primary },
  notifIcon: {
    width: hp(5.2),
    height: hp(5.2),
    borderRadius: hp(1.4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  notifBody: { flex: 1 },
  notifTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(0.5),
  },
  notifTitle: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  notifTime: { fontSize: hp(1.3), fontFamily: FONTS.fontFamilyRegular, color: COLORS.gray },
  notifText: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#666',
    lineHeight: hp(2.0),
  },
  unreadDot: {
    width: hp(0.9),
    height: hp(0.9),
    borderRadius: hp(0.5),
    backgroundColor: COLORS.primary,
    alignSelf: 'center',
  },

  // Permission UI Styles
  permissionContainer: {
    flex: 1,
    backgroundColor: COLORS.pageColor,
    justifyContent: 'center',
    paddingHorizontal: wp(10),
  },
  permissionContent: {
    alignItems: 'center',
    backgroundColor: COLORS.white,
    padding: wp(8),
    borderRadius: hp(3),
    elevation: 10,
    shadowColor: COLORS.black,
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  permissionIconCircle: {
    width: hp(12),
    height: hp(12),
    borderRadius: hp(6),
    backgroundColor: COLORS.primary100,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(3),
  },
  permissionTitle: {
    fontSize: hp(2.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    textAlign: 'center',
    marginBottom: hp(1.5),
  },
  permissionDesc: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray,
    textAlign: 'center',
    lineHeight: hp(2.3),
    marginBottom: hp(4),
  },
  permissionBtn: {
    width: '100%',
    backgroundColor: COLORS.charcoal,
    paddingVertical: hp(1.6),
    borderRadius: hp(1.6),
    alignItems: 'center',
    marginBottom: hp(1.5),
  },
  permissionBtnText: {
    fontSize: hp(1.8),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.white,
  },
  notNowBtn: {
    paddingVertical: hp(1),
  },
  notNowText: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.gray,
  },
});
