// Icon names from react-native-vector-icons/MaterialCommunityIcons
// Usage: <Icon name={icons.home} />
const icons = {
  home: 'home-variant-outline',
  homeActive: 'home-variant',
  user: 'account-outline',
  userActive: 'account',
  product: 'product-open-page-variant-outline',
  productActive: 'product-open-page-variant',
  star: 'star-circle-outline',
  starActive: 'star-circle',
  menu: 'view-dashboard-outline',
  menuActive: 'view-dashboard',
  address: 'map-marker-outline',
  orders: 'receipt',
  wallet: 'wallet-outline',
  support: 'headset',
  out: 'logout',
  notification: 'bell-outline',
  heart: 'heart-outline',
  heartActive: 'heart',
  search: 'magnify',
  filter: 'tune',
  eye: 'eye-outline',
  eyeOff: 'eye-off-outline',
  check: 'check-circle-outline',
  close: 'close-circle-outline',
  chevronRight: 'chevron-right',
  chevronLeft: 'chevron-left',
  phone: 'phone-outline',
  email: 'email-outline',
  lock: 'lock-outline',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
};

export default icons;
