import { StyleSheet } from 'react-native';
import { palette as p, typography as t } from '@/theme/tokens';
export const styles = StyleSheet.create({
  container: { marginBottom: 18, width: '100%' },
  label: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: t.medium,
    color: p.ink,
    flex: 1,
    textAlign: 'right',
  },
  requiredStar: { color: p.danger, flex: 0 },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: p.surface,
    minHeight: 54,
  },
  focused: { borderColor: p.primary, backgroundColor: '#FBFDFB' },
  input: {
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    lineHeight: 24,
    fontFamily: t.regular,
    color: p.ink,
    paddingVertical: 13,
    textAlign: 'right',
  },
  textArea: { minHeight: 100, textAlignVertical: 'top' },
  inputError: { borderColor: p.danger, backgroundColor: '#FFF9F8' },
  errorText: {
    color: p.danger,
    fontSize: 13,
    lineHeight: 21,
    fontFamily: t.regular,
    textAlign: 'right',
    marginTop: 5,
  },
});
