import { StyleSheet } from 'react-native';
import { palette as p, typography as t } from '@/theme/tokens';
export const styles = StyleSheet.create({
  list: { flex: 1 },
  content: { width: '100%', maxWidth: 840, alignSelf: 'center', paddingBottom: 16 },
  hero: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12, overflow: 'hidden' },
  brandRow: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between' },
  logo: { width: 43, height: 43 },
  role: {
    backgroundColor: '#EDF5EF',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  roleText: { fontSize: 11, color: p.primary },
  cartIcon: { minWidth: 46, minHeight: 46, justifyContent: 'center', alignItems: 'center' },
  badge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#E88D39',
    borderRadius: 12,
    minWidth: 20,
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  badgeText: { fontSize: 11, lineHeight: 20, color: '#fff', fontFamily: t.bold },
  title: { fontSize: 29, lineHeight: 40, fontFamily: t.bold, color: p.deep, marginTop: 9 },
  subtitle: { color: p.muted, fontSize: 13, lineHeight: 23 },
  motif: { position: 'absolute', left: 45, bottom: 5, opacity: 0.035 },
  sticky: { backgroundColor: p.background, paddingHorizontal: 20, paddingTop: 6, paddingBottom: 5 },
  searchRow: { flexDirection: 'row-reverse', gap: 10, alignItems: 'center' },
  searchBox: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 14,
    minHeight: 48,
    paddingHorizontal: 12,
    gap: 8,
  },
  search: {
    flex: 1,
    minWidth: 0,
    textAlign: 'right',
    fontFamily: t.regular,
    fontSize: 13,
    color: p.ink,
    minHeight: 46,
  },
  clear: { minWidth: 32, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  filterButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: p.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categories: { flexDirection: 'row-reverse', gap: 8, paddingVertical: 10, flexGrow: 1 },
  pill: {
    backgroundColor: '#F0F4EF',
    borderWidth: 1,
    borderColor: '#E2EAE2',
    borderRadius: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  pillActive: { backgroundColor: p.primary, borderColor: p.primary },
  pillText: { color: p.deep, fontSize: 12 },
  white: { color: '#fff' },
  chips: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 6, paddingBottom: 8 },
  chip: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#E4F1E9',
    borderRadius: 9,
    paddingHorizontal: 10,
    minHeight: 36,
  },
  chipText: { fontSize: 11, color: p.primary },
  toolbar: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
  },
  sectionTitle: { fontSize: 20, fontFamily: t.bold, color: p.deep },
  count: { fontSize: 11, color: p.muted },
  toggle: {
    flexDirection: 'row',
    backgroundColor: '#EFF3EE',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 11,
    overflow: 'hidden',
  },
  toggleButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  activeToggle: { backgroundColor: p.primary },
  rows: { paddingHorizontal: 20, gap: 12, paddingBottom: 12 },
  row: { flexDirection: 'row-reverse', gap: 12 },
  spacer: { flex: 1 },
  state: { padding: 28, alignItems: 'center', gap: 12 },
  stateTitle: { fontSize: 19, fontFamily: t.bold, color: p.deep, textAlign: 'center' },
  stateText: { fontSize: 13, color: p.muted, textAlign: 'center' },
  retry: {
    minHeight: 44,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: p.soft,
    borderRadius: 12,
  },
  retryText: { color: p.primary, fontFamily: t.bold },
  progress: {
    paddingHorizontal: 20,
    paddingBottom: 10,
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    gap: 8,
    alignItems: 'center',
  },
  progressText: { fontSize: 11, color: p.muted, flexShrink: 1 },
  cartBar: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 16,
    overflow: 'hidden',
    width: 'auto',
    maxWidth: 800,
  },
  cartInner: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 54,
    paddingHorizontal: 16,
    gap: 8,
  },
  cartGroup: { flexDirection: 'row-reverse', alignItems: 'center', gap: 9 },
  cartText: { fontFamily: t.bold, color: '#fff', fontSize: 14 },
  skeleton: { flex: 1, padding: 10, backgroundColor: '#fff', borderRadius: 18, gap: 10 },
  skeletonImage: { height: 125, backgroundColor: '#EBEFEB', borderRadius: 12 },
  skeletonLine: { height: 12, backgroundColor: '#EBEFEB', borderRadius: 5 },
});
