import { StyleSheet } from 'react-native';
import { typography as t } from '@/theme/tokens';
import { catalogPalette as p } from '@/components/shared/catalog/catalog-theme';
export const styles = StyleSheet.create({
  list: { flex: 1 },
  content: { width: '100%', maxWidth: 960, alignSelf: 'center', paddingBottom: 28 },
  hero: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  heading: { flex: 1 },
  title: { fontSize: 32, lineHeight: 46, fontFamily: t.bold, color: p.deep },
  subtitle: { color: p.muted, fontSize: 13, lineHeight: 23, marginTop: 2 },
  headerControls: { alignItems: 'center', gap: 10 },
  brand: { flexDirection: 'row-reverse', alignItems: 'center', gap: 6 },
  logo: { width: 27, height: 27 },
  brandName: { fontSize: 22, lineHeight: 30, fontFamily: t.bold, color: p.deep },
  toggle: { flexDirection: 'row', gap: 6 },
  toggleButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FCFBF9',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 12,
  },
  activeToggle: { backgroundColor: p.soft, borderColor: '#D6E3DA' },
  pressed: { opacity: 0.65 },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: p.primary,
    borderRadius: 12,
    minWidth: 20,
    alignItems: 'center',
    paddingHorizontal: 3,
    borderWidth: 2,
    borderColor: p.background,
  },
  badgeText: { fontSize: 10, lineHeight: 17, color: '#fff', fontFamily: t.bold },
  sticky: { backgroundColor: p.background, paddingHorizontal: 16, paddingTop: 4, paddingBottom: 2 },
  searchRow: { flexDirection: 'row-reverse', gap: 8, alignItems: 'center' },
  searchBox: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 13,
    minHeight: 50,
    paddingHorizontal: 12,
    gap: 8,
  },
  search: {
    flex: 1,
    minWidth: 0,
    textAlign: 'right',
    fontFamily: t.regular,
    fontSize: 13,
    color: p.ink,
    minHeight: 48,
  },
  clear: { minWidth: 32, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  filterButton: {
    width: 50,
    height: 50,
    borderRadius: 13,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: p.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categories: { flexDirection: 'row-reverse', gap: 8, paddingVertical: 14, flexGrow: 1 },
  pill: {
    backgroundColor: '#FCFBF9',
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 24,
    paddingHorizontal: 20,
    minHeight: 44,
    justifyContent: 'center',
  },
  pillActive: { backgroundColor: p.primary, borderColor: p.primary },
  pillText: { color: p.ink, fontSize: 13, fontFamily: t.medium },
  white: { color: '#fff' },
  chips: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 6, paddingBottom: 8 },
  chip: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
    backgroundColor: p.soft,
    borderRadius: 22,
    paddingHorizontal: 12,
    minHeight: 44,
  },
  chipText: { fontSize: 12, color: p.primary },
  toolbar: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    paddingBottom: 6,
  },
  results: { flexShrink: 1 },
  count: { fontSize: 12, lineHeight: 22, color: p.muted },
  sortButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
    minHeight: 44,
    flexShrink: 1,
  },
  sortText: { fontSize: 12, fontFamily: t.medium, color: p.ink, flexShrink: 1 },
  rows: { paddingHorizontal: 16, gap: 10, paddingBottom: 10 },
  row: { flexDirection: 'row-reverse', gap: 10 },
  spacer: { flex: 1 },
  state: { padding: 28, alignItems: 'center', gap: 12 },
  stateTitle: { fontSize: 19, fontFamily: t.bold, color: p.deep, textAlign: 'center' },
  stateText: { fontSize: 13, color: p.muted, textAlign: 'center' },
  retry: {
    minHeight: 44,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: p.soft,
    borderRadius: 12,
  },
  retryText: { color: p.primary, fontFamily: t.bold },
  progress: {
    paddingHorizontal: 20,
    paddingBottom: 10,
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    gap: 8,
    alignItems: 'center',
  },
  progressText: { fontSize: 11, color: p.muted, flexShrink: 1 },
  skeleton: {
    flex: 1,
    padding: 6,
    backgroundColor: '#fff',
    borderRadius: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: p.border,
  },
  skeletonImage: { aspectRatio: 1, backgroundColor: p.photo, borderRadius: 13 },
  skeletonLine: { height: 14, backgroundColor: p.photo, borderRadius: 5, marginHorizontal: 5 },
});
