import { COLORS, FONTS, hp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.pageColor },
  flatContent: { paddingHorizontal: hp(1.9), paddingBottom: hp(10) },
  columnWrapper: { justifyContent: 'space-between' },
  listHeader: {
    paddingTop: hp(1.9),
  },
  archiveTabs: {
    flexDirection: 'row',
    backgroundColor: COLORS.bordercolor,
    borderRadius: hp(1.4),
    padding: hp(0.5),
    marginBottom: hp(1.9),
  },
  archiveTab: { flex: 1, paddingVertical: hp(1.2), alignItems: 'center', borderRadius: hp(1.2) },
  archiveTabActive: {
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  archiveTabText: { fontSize: hp(1.4), fontFamily: FONTS.fontFamilyMedium, color: COLORS.darkgray },
  archiveTabTextActive: { fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },

  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(1.9),
  },
  screenTitle: { fontSize: hp(2.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  sortBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: hp(0.9),
    borderRadius: hp(0.9),
    borderWidth: 1,
    borderColor: COLORS.bordercolor,
    backgroundColor: COLORS.white,
  },
  sortBtnText: { fontSize: hp(1.3), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },

  searchRow: { flexDirection: 'row', gap: hp(1.4), marginBottom: hp(1.9) },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: hp(1.6),
    paddingHorizontal: hp(1.6),
    paddingVertical: hp(1.4),
    gap: 10,
    elevation: 1,
    shadowColor: COLORS.black,
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.charcoal,
  },
  filterIconBtn: {
    width: hp(5.6),
    height: hp(5.6),
    borderRadius: hp(1.6),
    backgroundColor: COLORS.charcoal,
    justifyContent: 'center',
    alignItems: 'center',
  },

  categoryRow: { gap: hp(0.9), marginBottom: hp(1.9) },
  pill: {
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(0.9),
    borderRadius: hp(2.4),
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.bordercolor,
  },
  pillActive: { backgroundColor: COLORS.charcoal, borderColor: COLORS.charcoal },
  pillText: { fontSize: hp(1.4), fontFamily: FONTS.fontFamilyMedium, color: '#666' },
  pillTextActive: { color: COLORS.white, fontFamily: FONTS.fontFamilyBold },

  resultsCount: {
    fontSize: hp(1.3),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.gray,
    marginBottom: hp(1.4),
  },

  empty: { alignItems: 'center', paddingTop: hp(7.1) },
  emptyTitle: {
    fontSize: hp(1.9),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.gray,
    marginTop: hp(1.9),
    marginBottom: hp(2.4),
  },
  resetBtn: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: hp(2.8),
    paddingVertical: hp(1.4),
    borderRadius: hp(3.5),
  },
  resetBtnText: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.white },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  sortSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: hp(2.8),
    borderTopRightRadius: hp(2.8),
    padding: hp(2.4),
    paddingBottom: hp(4.7),
  },
  sheetHandle: {
    width: hp(4.7),
    height: hp(0.5),
    backgroundColor: COLORS.bordercolor,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: hp(2.4),
  },
  sheetTitle: {
    fontSize: hp(2.1),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(1.9),
  },
  sortOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp(1.9),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  sortOptionActive: { backgroundColor: '#FFF9F6' },
  sortOptionText: {
    fontSize: hp(1.8),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.charcoal,
  },
  sortOptionTextActive: { fontFamily: FONTS.fontFamilyBold, color: COLORS.primary },

  // Pagination
  paginationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp(2.5),
    marginBottom: hp(2),
    paddingVertical: hp(1.2),
    paddingHorizontal: hp(1.8),
    backgroundColor: COLORS.white,
    borderRadius: hp(1.8),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  pageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: hp(1.6),
    paddingVertical: hp(0.9),
    borderRadius: hp(1),
    backgroundColor: '#F1F5F9',
  },
  pageBtnDisabled: {
    opacity: 0.4,
  },
  pageBtnText: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  pageIndicator: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.darkgray,
  },
  footerLoader: {
    paddingVertical: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
});
