import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.lightGrey },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(1.4),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray4,
  },
  backBtn: {
    width: hp(4.2),
    height: hp(4.2),
    borderRadius: hp(1.2),
    borderWidth: 1,
    borderColor: COLORS.gray5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: hp(2.0),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  countBadge: {
    width: hp(4.2),
    textAlign: 'center',
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  grid: { paddingHorizontal: hp(1.4), paddingTop: hp(1.9), paddingBottom: hp(4.7) },
  card: {
    width: wp(45),
    backgroundColor: COLORS.white,
    borderRadius: hp(1.6),
    overflow: 'hidden',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
  },
  heartBtn: {
    position: 'absolute',
    top: hp(0.9),
    right: hp(0.9),
    zIndex: 10,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: hp(1.6),
    padding: hp(0.5),
  },
  cover: { width: '100%', height: hp(17.6), justifyContent: 'center', alignItems: 'center' },
  info: { padding: hp(1.2) },
  productTitle: {
    fontSize: hp(1.5),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(0.4),
  },
  productAuthor: {
    fontSize: hp(1.2),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray,
    marginBottom: hp(0.9),
  },
  footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  ratingText: { fontSize: hp(1.2), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  addBtn: {
    width: hp(3.3),
    height: hp(3.3),
    borderRadius: hp(0.9),
    backgroundColor: COLORS.charcoal,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
