import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.pageColor },
  scrollContent: { paddingBottom: hp(5) },

  // Header
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    backgroundColor: COLORS.pageColor,
  },
  headerLeft: { flex: 1 },
  greetingSmall: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray2,
  },
  greetingName: { fontSize: hp(2.0), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconActionBtn: {
    width: hp(4.5),
    height: hp(4.5),
    borderRadius: hp(1.4),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  notifDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.mainOrange,
    borderWidth: 1.5,
    borderColor: COLORS.white,
  },
  avatarCircle: {
    width: hp(4.5),
    height: hp(4.5),
    borderRadius: hp(2.2),
    backgroundColor: COLORS.mainOrange,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarLetter: { fontSize: hp(1.9), fontFamily: FONTS.fontFamilyBold, color: COLORS.white },

  // Wallets
  walletsRow: {
    paddingHorizontal: wp(5),
    marginBottom: hp(2.5),
  },
  walletCardFull: {
    borderRadius: hp(2),
    padding: hp(2),
    elevation: 4,
    shadowColor: '#1E293B',
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  walletHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(1.5),
  },
  walletHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
  },
  walletIconBox: {
    width: hp(4.2),
    height: hp(4.2),
    borderRadius: hp(1.2),
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletLabel: {
    fontSize: hp(1.6),
    color: COLORS.white,
    fontFamily: FONTS.fontFamilyBold,
  },
  walletCurrency: {
    fontSize: hp(1.25),
    color: 'rgba(255,255,255,0.7)',
    fontFamily: FONTS.fontFamilyRegular,
    marginTop: 2,
  },
  balanceValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  walletBalanceAmount: {
    fontSize: hp(3.2),
    color: COLORS.white,
    fontFamily: FONTS.fontFamilyBold,
  },
  walletCurrencySymbol: {
    fontSize: hp(2.0),
    color: COLORS.mainOrange,
    fontFamily: FONTS.fontFamilyBold,
  },

  // Latest Orders
  latestOrdersContainer: { paddingHorizontal: wp(5), marginBottom: hp(2.5) },
  miniOrderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    padding: hp(1.4),
    borderRadius: hp(1.6),
    marginBottom: hp(1),
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  orderIconBox: {
    width: hp(4.7),
    height: hp(4.7),
    borderRadius: hp(1.2),
    backgroundColor: '#FFF1F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hp(1.2),
  },
  orderInfo: { flex: 1 },
  orderCustomer: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  orderDate: {
    fontSize: hp(1.3),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray2,
    marginTop: 2,
  },
  orderAmountBox: { alignItems: 'flex-end' },
  orderAmount: { fontSize: hp(1.6), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  orderStatus: { fontSize: hp(1.2), fontFamily: FONTS.fontFamilyBold, marginTop: 2 },

  // Section Header
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(5),
    marginBottom: hp(1.5),
  },
  sectionTitle: { fontSize: hp(2.0), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  seeAll: { fontSize: hp(1.5), fontFamily: FONTS.fontFamilySemiBold, color: COLORS.mainOrange },

  tabsRow: { paddingHorizontal: wp(5), gap: hp(0.9), marginBottom: hp(2), marginTop: hp(0.5) },
  tabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(0.9),
    borderRadius: hp(2.4),
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.bordercolor,
  },
  tabBtnActive: { backgroundColor: COLORS.charcoal, borderColor: COLORS.charcoal },
  tabText: { fontSize: hp(1.4), fontFamily: FONTS.fontFamilyMedium, color: COLORS.darkgray },
  tabTextActive: { color: COLORS.white, fontFamily: FONTS.fontFamilyBold },
});
