import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scroll: { paddingBottom: hp(10) },

  avatarSection: {
    alignItems: 'center',
    paddingVertical: hp(3.5),
    backgroundColor: COLORS.white,
    borderBottomLeftRadius: hp(3),
    borderBottomRightRadius: hp(3),
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  avatarContainer: {
    width: hp(11),
    height: hp(11),
    borderRadius: hp(3),
    backgroundColor: COLORS.white,
    elevation: 6,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFEDD5',
  },
  avatarPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  avatarText: { fontSize: hp(4), fontFamily: FONTS.fontFamilyBold, color: COLORS.mainOrange },

  userName: {
    fontSize: hp(2.2),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginTop: hp(1.5),
  },
  userRole: {
    fontSize: hp(1.5),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#64748B',
    marginTop: 3,
  },

  badgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: wp(2),
    marginTop: hp(1),
  },
  roleBadge: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.4),
    borderRadius: hp(1),
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  roleBadgeText: {
    fontSize: hp(1.3),
    color: COLORS.mainOrange,
    fontFamily: FONTS.fontFamilyBold,
  },
  statusBadge: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.4),
    borderRadius: hp(1),
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  statusBadgeText: {
    fontSize: hp(1.3),
    color: '#10B981',
    fontFamily: FONTS.fontFamilyBold,
  },

  editProfileCta: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    marginTop: hp(2),
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.9),
    borderRadius: hp(2),
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  editProfileCtaText: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.mainOrange,
  },

  form: { padding: wp(4) },
  infoBox: {
    backgroundColor: COLORS.white,
    borderRadius: hp(2),
    padding: wp(4),
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: hp(1.7),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.mainOrange,
    marginBottom: hp(1.5),
    textAlign: 'left',
  },

  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
    paddingVertical: hp(1.2),
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  infoCol: {
    flex: 1,
  },
  infoLabel: {
    fontSize: hp(1.25),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#94A3B8',
    marginBottom: 2,
  },
  infoValue: {
    fontSize: hp(1.55),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.charcoal,
  },

  saveSection: { paddingHorizontal: wp(4), marginTop: hp(1) },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: hp(1.8),
    borderRadius: hp(1.5),
    borderWidth: 1.5,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
  },
  logoutText: {
    fontSize: hp(1.8),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.error,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
  },
  menuIconBox: {
    width: hp(4),
    height: hp(4),
    borderRadius: hp(1),
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemLabel: {
    fontSize: hp(1.5),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.charcoal,
  },
});
