import { COLORS, FONTS, hp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.lightGrey },
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(1.4),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray4,
  },
  backBtn: {
    width: hp(4.2),
    height: hp(4.2),
    borderRadius: hp(1.2),
    borderWidth: 1,
    borderColor: COLORS.gray5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: hp(2.0),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  scroll: { padding: hp(1.9), paddingBottom: hp(4.7) },
  hero: {
    backgroundColor: COLORS.white,
    borderRadius: hp(2.1),
    padding: hp(2.8),
    alignItems: 'center',
    marginBottom: hp(2.4),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  heroIcon: {
    width: hp(8.2),
    height: hp(8.2),
    borderRadius: hp(4.1),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(1.4),
  },
  heroTitle: {
    fontSize: hp(2.4),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(0.9),
  },
  heroSubtitle: {
    fontSize: hp(1.5),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray2,
    textAlign: 'center',
    lineHeight: hp(2.4),
  },
  contactCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: hp(1.6),
    padding: hp(1.9),
    marginBottom: hp(1.2),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  iconBox: {
    width: hp(5.6),
    height: hp(5.6),
    borderRadius: hp(1.6),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hp(1.6),
  },
  contactInfo: { flex: 1 },
  contactLabel: {
    fontSize: hp(1.8),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: 2,
  },
  contactSubtitle: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray,
  },
  infoCard: {
    backgroundColor: COLORS.primary100,
    borderRadius: hp(1.6),
    padding: hp(1.9),
    alignItems: 'center',
    marginTop: hp(0.9),
  },
  infoText: {
    fontSize: hp(1.4),
    fontFamily: FONTS.fontFamilyRegular,
    color: COLORS.darkgray2,
    textAlign: 'center',
    marginBottom: 4,
  },
});
