import { COLORS, FONTS, hp, wp } from '@/theme/index';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.lightGrey },
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: hp(1.9),
    paddingVertical: hp(1.4),
    backgroundColor: COLORS.pageColor,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray4,
  },
  backBtn: {
    width: hp(4.2),
    height: hp(4.2),
    borderRadius: hp(1.2),
    borderWidth: 1,
    borderColor: COLORS.gray5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: hp(2.0),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  scroll: { padding: 20, paddingBottom: 150, width: '100%', maxWidth: 680, alignSelf: 'center' },
  sectionLabel: {
    fontSize: 18,
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
    marginBottom: hp(1.4),
    marginTop: hp(1.9),
  },

  customerCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: hp(1.9),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0,
    shadowRadius: 4,
    elevation: 0,
    borderWidth: 1,
    borderColor: COLORS.bordercolor,
  },

  optionCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: hp(1.4),
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: hp(1.6),
    marginBottom: hp(1.2),
    borderWidth: 1.5,
    borderColor: COLORS.bordercolor,
  },
  optionCardActive: { borderColor: COLORS.primary },
  radio: {
    width: hp(2.1),
    height: hp(2.1),
    borderRadius: hp(1.1),
    borderWidth: 2,
    borderColor: '#DDD',
    backgroundColor: COLORS.white,
  },
  radioActive: {
    width: hp(2.1),
    height: hp(2.1),
    borderRadius: hp(1.1),
    borderWidth: 5,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
  },
  optionIcon: {
    width: hp(4.7),
    height: hp(4.7),
    borderRadius: hp(1.2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionLabel: {
    flex: 1,
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },

  summaryBox: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: hp(1.9),
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0,
    shadowRadius: 4,
    elevation: 0,
    borderWidth: 1,
    borderColor: COLORS.bordercolor,
  },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: hp(1.2) },
  summaryLabel: { fontSize: hp(1.5), fontFamily: FONTS.fontFamilyRegular, color: COLORS.darkgray },
  summaryValue: { fontSize: hp(1.5), fontFamily: FONTS.fontFamilySemiBold, color: '#555' },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: COLORS.bordercolor,
    paddingTop: hp(1.4),
    marginTop: hp(0.5),
    marginBottom: 0,
  },
  totalLabel: { fontSize: hp(1.8), fontFamily: FONTS.fontFamilyBold, color: COLORS.charcoal },
  totalValue: { fontSize: hp(2.1), fontFamily: FONTS.fontFamilyBold, color: COLORS.primary },

  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    paddingHorizontal: hp(1.9),
    paddingTop: hp(1.4),
    borderTopWidth: 1,
    borderTopColor: COLORS.gray4,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: hp(1.4),
  },
  footerTotal: { flex: 1, alignItems: 'flex-end' },
  footerTotalLabel: { fontSize: hp(1.3), fontFamily: FONTS.fontFamilyRegular, color: COLORS.gray },
  footerTotalValue: {
    fontSize: hp(2.1),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.primary,
  },
  placeOrderBtn: {
    borderRadius: 16,
    overflow: 'hidden',
    width: '55%',
  },
  placeOrderText: { fontSize: hp(1.8), fontFamily: FONTS.fontFamilyBold, color: COLORS.white },

  // Area Modal
  areaPickerInput: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.gray5 || '#E2E8F0',
    borderRadius: hp(1.2),
    paddingHorizontal: wp(3.5),
    paddingVertical: hp(1.4),
    backgroundColor: '#F8FAFC',
    marginBottom: hp(1.5),
  },
  areaPickerText: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.charcoal,
  },
  areaPickerPlaceholder: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyRegular,
    color: '#94A3B8',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: hp(2.5),
    borderTopRightRadius: hp(2.5),
    padding: hp(2.5),
    maxHeight: hp(65),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    marginBottom: hp(1.5),
  },
  modalTitle: {
    fontSize: hp(1.9),
    fontFamily: FONTS.fontFamilyBold,
    color: COLORS.charcoal,
  },
  areaItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(1.6),
    paddingHorizontal: wp(2),
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  areaItemActive: {
    backgroundColor: '#EDF6F1',
    borderRadius: hp(1),
  },
  areaItemText: {
    fontSize: hp(1.6),
    fontFamily: FONTS.fontFamilyMedium,
    color: COLORS.charcoal,
  },
  areaItemTextActive: {
    color: COLORS.primary,
    fontFamily: FONTS.fontFamilyBold,
  },
});
