import { StyleSheet } from 'react-native';
import { palette as p, typography as t } from '@/theme/tokens';
export const s = StyleSheet.create({
  page: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    padding: 18,
    gap: 18,
    paddingBottom: 28,
  },
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    minHeight: 60,
  },
  icon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: p.soft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 22, lineHeight: 32, fontFamily: t.bold, color: p.deep, textAlign: 'right' },
  hero: { backgroundColor: p.deep, padding: 22, borderRadius: 24, gap: 8 },
  heroTitle: {
    fontSize: 24,
    lineHeight: 36,
    color: '#fff',
    fontFamily: t.bold,
    textAlign: 'right',
  },
  heroText: { color: '#D4EADF', fontSize: 14, lineHeight: 24, textAlign: 'right' },
  card: {
    backgroundColor: p.surface,
    borderWidth: 1,
    borderColor: p.border,
    borderRadius: 22,
    padding: 18,
    gap: 16,
  },
  section: { flexDirection: 'row-reverse', gap: 12, alignItems: 'center', flexWrap: 'wrap' },
  number: {
    backgroundColor: p.soft,
    color: p.primary,
    borderRadius: 12,
    padding: 10,
    fontFamily: t.bold,
  },
  subtitle: { fontSize: 18, lineHeight: 28, fontFamily: t.bold, color: p.deep, textAlign: 'right' },
  caption: { color: p.muted, fontSize: 13, lineHeight: 22, textAlign: 'right' },
  field: { gap: 7 },
  label: { color: p.ink, fontFamily: t.medium, fontSize: 14, textAlign: 'right' },
  input: {
    borderWidth: 1,
    borderColor: p.border,
    backgroundColor: '#F8FAF7',
    borderRadius: 12,
    minHeight: 48,
    paddingHorizontal: 13,
    paddingVertical: 12,
    color: p.ink,
    fontFamily: t.regular,
    fontSize: 16,
    textAlign: 'right',
  },
  invalid: { borderColor: p.danger },
  error: { color: p.danger, fontSize: 13, lineHeight: 22, textAlign: 'right' },
  alert: { padding: 14, borderRadius: 14, backgroundColor: '#FFF0EB', gap: 10 },
  row: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  money: {
    color: p.deep,
    fontFamily: t.bold,
    fontSize: 20,
    lineHeight: 30,
    writingDirection: 'ltr',
  },
  item: { borderWidth: 1, borderColor: p.border, borderRadius: 16, padding: 14, gap: 14 },
  itemName: {
    fontFamily: t.bold,
    fontSize: 16,
    lineHeight: 26,
    color: p.deep,
    textAlign: 'right',
    flexShrink: 1,
  },
  photo: { width: 52, height: 52, borderRadius: 12, backgroundColor: p.soft },
  qty: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10 },
  qtyInput: { flex: 1, textAlign: 'center' },
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderColor: p.border,
    backgroundColor: p.surface,
    gap: 10,
  },
  overlay: { flex: 1, backgroundColor: 'rgba(8,35,29,.45)', justifyContent: 'flex-end' },
  sheet: {
    maxHeight: '94%',
    backgroundColor: p.background,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    padding: 18,
    gap: 14,
  },
  pickerRow: {
    flexDirection: 'row-reverse',
    gap: 12,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: p.border,
    alignItems: 'center',
  },
  disabled: { opacity: 0.45 },
  badge: { backgroundColor: p.soft, padding: 8, borderRadius: 9, color: p.primary, fontSize: 12 },
});
