import { StyleSheet } from 'react-native';
import { palette as p, typography as t } from '@/theme/tokens';
export const s = StyleSheet.create({
  page: {
    padding: 18,
    gap: 20,
    paddingBottom: 32,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  heading: { fontFamily: t.bold, fontSize: 25, lineHeight: 36, color: p.deep, textAlign: 'right' },
  title: { fontFamily: t.bold, fontSize: 19, lineHeight: 29, color: p.deep, textAlign: 'right' },
  caption: { fontSize: 12, lineHeight: 21, color: p.muted, textAlign: 'right' },
  link: { fontFamily: t.bold, fontSize: 13, color: p.primary },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: p.deep,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initials: { fontFamily: t.bold, fontSize: 22, color: '#fff' },
  brand: { fontFamily: t.bold, fontSize: 24, color: p.deep },
  card: {
    padding: 18,
    borderWidth: 1,
    borderColor: '#E7EEE8',
    borderRadius: 24,
    backgroundColor: '#fff',
    gap: 14,
  },
  balance: { padding: 22, borderRadius: 25, gap: 12, overflow: 'hidden' },
  balanceLabel: { color: '#D0E7DA', fontFamily: t.medium, fontSize: 16, textAlign: 'right' },
  amount: {
    color: '#fff',
    fontSize: 39,
    lineHeight: 55,
    fontFamily: t.bold,
    writingDirection: 'ltr',
    textAlign: 'right',
  },
  balanceMeta: { color: '#D0E7DA', fontSize: 12, lineHeight: 21, textAlign: 'right' },
  icon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#ffffff30',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stats: { flexDirection: 'row-reverse', gap: 8, flexWrap: 'wrap' },
  stat: {
    flex: 1,
    minWidth: 80,
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E7EEE8',
    backgroundColor: '#fff',
    gap: 8,
    alignItems: 'center',
  },
  statNumber: { fontSize: 27, lineHeight: 38, fontFamily: t.bold, color: p.deep },
  segmented: {
    flexDirection: 'row-reverse',
    backgroundColor: '#F0F3F0',
    borderRadius: 12,
    padding: 3,
  },
  segment: {
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  chart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 150,
    gap: 7,
    borderBottomWidth: 1,
    borderColor: p.border,
    paddingHorizontal: 3,
  },
  barSlot: { flex: 1, height: 148, justifyContent: 'flex-end', alignItems: 'center', minWidth: 27 },
  bar: {
    width: '78%',
    maxWidth: 40,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: '#C6E7DB',
  },
  barText: { fontSize: 11, lineHeight: 18, color: p.muted },
  alert: { color: p.danger, fontSize: 13, lineHeight: 22, textAlign: 'right' },
  orderRow: { paddingVertical: 15, gap: 10, borderBottomWidth: 1, borderColor: '#EAF0EB' },
  orderName: {
    fontFamily: t.medium,
    fontSize: 15,
    color: p.ink,
    textAlign: 'right',
    flexShrink: 1,
  },
  money: { color: p.deep, fontFamily: t.bold, fontSize: 15, writingDirection: 'ltr' },
  status: { borderRadius: 10, paddingHorizontal: 9, paddingVertical: 4 },
  empty: { paddingVertical: 18, gap: 10, alignItems: 'center' },
  skeleton: { height: 16, backgroundColor: '#EAF0EB', borderRadius: 8 },
});
